# Generated by Django 5.1 on 2024-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('password', models.CharField(blank=True, max_length=35, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Prefer Not to Say', 'prefer not to say')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=25, null=True)),
                ('Designation', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
