# Generated by Django 5.1 on 2024-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_registration',
            name='Designation',
        ),
        migrations.AddField(
            model_name='staff_registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_registration',
            name='department',
            field=models.CharField(blank=True, choices=[('Information_Technology', 'INFORMATION_TECHNOLOGY'), ('Computer_Science', 'COMPUTER_SCIENCE'), ('Computer_Technology', 'COMPUTER_TECHNOLOGY')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='staff_registration',
            name='designation',
            field=models.CharField(blank=True, choices=[('HOD', 'HOD'), ('Assistant_Professor', 'ASSISTANT PROFESSOR'), ('Professor', 'PROFESSOR')], max_length=25, null=True),
        ),
    ]
