# Generated by Django 5.1 on 2024-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_remove_staff_registration_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('department', models.CharField(blank=True, choices=[('Information_Technology', 'INFORMATION_TECHNOLOGY'), ('Computer_Science', 'COMPUTER_SCIENCE'), ('Computer_Technology', 'COMPUTER_TECHNOLOGY')], max_length=25, null=True)),
                ('semester', models.CharField(blank=True, max_length=15, null=True)),
                ('rollno', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Prefer Not to Say', 'prefer not to say')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=35, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
