# Generated by Django 5.1 on 2024-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_student_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizer_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer not to say')], max_length=20, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='department',
            field=models.CharField(blank=True, choices=[('Information_Technology', 'INFORMATION_TECHNOLOGY'), ('Computer_Science', 'COMPUTER_SCIENCE'), ('Computer_Technology', 'COMPUTER_TECHNOLOGY')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
