# Generated by Django 5.1 on 2024-12-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_organizer_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer_registration',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
