# Generated by Django 5.1 on 2024-12-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_rename_mobile_organizer_registration_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
