# Generated by Django 5.1 on 2024-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventsimg')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('resultdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
