# Generated by Django 5.1 on 2024-12-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_feedback_delete_eventsdes_delete_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('eventname', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventsimg')),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('eventdate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('registerenddate', models.DateField(auto_now_add=True, null=True)),
                ('resultdate', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeapp.staff_registration')),
            ],
        ),
        migrations.CreateModel(
            name='eventparticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_status', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.student_registration')),
                ('eventname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.eventsupdates')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.eventsupdates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.student_registration')),
            ],
        ),
    ]
