# Generated by Django 5.1 on 2024-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_eventsupdates_eventparticipants_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsupdates',
            name='approved',
        ),
        migrations.AddField(
            model_name='eventsupdates',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='eventsupdates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eventsimg/'),
        ),
        migrations.AlterField(
            model_name='eventsupdates',
            name='registerenddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
