# Generated by Django 5.1 on 2024-12-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_eventsupdates_msg_alter_eventsupdates_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='events',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='eventsupdates',
            name='organizer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.organizer_registration'),
        ),
        migrations.DeleteModel(
            name='eventparticipants',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
