# Generated by Django 5.1 on 2024-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_remove_payment_events_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='createevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_created', models.DateField(auto_created=True)),
                ('event_category', models.CharField(choices=[('games', 'Games'), ('entertainment', 'Entertainment'), ('food fest', 'Food Fest'), ('workshops', 'Workshops')], max_length=28)),
                ('version', models.CharField(choices=[('Paid', 'PAID'), ('Free', 'FREE')], max_length=10)),
                ('event_name', models.CharField(max_length=50)),
                ('events_description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('image', models.ImageField(upload_to='events/')),
                ('doe', models.DateField()),
                ('rend', models.DateField()),
                ('resultdate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsupdates',
            name='organizer_user',
        ),
        migrations.RemoveField(
            model_name='eventsupdates',
            name='staff_user',
        ),
        migrations.DeleteModel(
            name='organizer_Registration',
        ),
        migrations.DeleteModel(
            name='eventsupdates',
        ),
    ]
