# Generated by Django 5.1 on 2025-01-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_createevents_remove_eventsupdates_organizer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevents',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
