# Generated by Django 5.1 on 2025-01-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_alter_createevents_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevents',
            name='event_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
