# Generated by Django 5.1 on 2025-01-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_alter_createevents_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevents',
            name='doe',
            field=models.DateField(unique=True),
        ),
        migrations.CreateModel(
            name='staffallocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('event_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.createevents')),
                ('staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.staff_registration')),
            ],
        ),
    ]
