# Generated by Django 5.1 on 2025-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_alter_createevents_doe_staffallocate'),
    ]

    operations = [
        migrations.CreateModel(
            name='judgeregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Prefer Not to Say', 'Prefer not to say')], max_length=17)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('profilepic', models.ImageField(upload_to='judgeprofile/')),
            ],
        ),
        migrations.AddField(
            model_name='staff_registration',
            name='pic',
            field=models.ImageField(default=1, upload_to='staffpic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='pic',
            field=models.ImageField(default=1, upload_to='studentpic/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createevents',
            name='event_category',
            field=models.CharField(choices=[('games', 'Games'), ('entertainment', 'Entertainment'), ('seminar', 'Seminar'), ('workshops', 'Workshops')], max_length=28),
        ),
    ]
