# Generated by Django 5.1 on 2025-01-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_judgeregister_staff_registration_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstatus', models.CharField(choices=[('booked', 'Booked'), ('unplan', 'Unplan')], max_length=21)),
                ('booking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.createevents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.student_registration')),
            ],
        ),
    ]
