# Generated by Django 5.1 on 2025-01-09 16:27

from django.db import migrations, models

import django.utils.timezone
class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_events_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_participants',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events_participants',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events_participants',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
