# Generated by Django 5.1 on 2025-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0020_alter_events_participants_created_at_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_participants',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='not paid', max_length=20),
        ),
    ]
