# Generated by Django 5.1 on 2025-01-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_alter_events_participants_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_description', models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place')], max_length=255)),
                ('prize_amount', models.IntegerField(blank=True, null=True)),
                ('awarded_on', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.createevents')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.judgeregister')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.events_participants')),
            ],
        ),
    ]
