# Generated by Django 5.1 on 2025-01-20 09:54

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0023_judgeregister_experience_judgeregister_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualifications',
            },
        ),
        migrations.AlterModelOptions(
            name='judgeregister',
            options={'verbose_name': 'judge register', 'verbose_name_plural': 'judge registers'},
        ),
        migrations.RemoveField(
            model_name='judgeregister',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer Not to Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='jname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='judgeregister',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='homeapp.qualification'),
        ),
    ]
