# Generated by Django 5.1 on 2025-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0024_qualification_alter_judgeregister_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeregister',
            name='qualifications',
        ),
        migrations.AlterModelOptions(
            name='judgeregister',
            options={},
        ),
        migrations.AddField(
            model_name='judgeregister',
            name='qualification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Prefer Not to Say', 'Prefer not to say')], max_length=17),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='jname',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='judgeregister',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='qualification',
        ),
    ]
