# Generated by Django 5.1 on 2025-01-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0025_remove_judgeregister_qualifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='judgeallocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('event_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.createevents')),
                ('judgename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.judgeregister')),
            ],
        ),
    ]
