# Generated by Django 5.1 on 2025-01-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0026_judgeallocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='prize_amount',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='prize_description',
        ),
        migrations.AddField(
            model_name='prize',
            name='participant1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prize_participant1', to='homeapp.events_participants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='participant2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prize_participant2', to='homeapp.events_participants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='participant3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prize_participant3', to='homeapp.events_participants'),
            preserve_default=False,
        ),
    ]
