# Generated by Django 5.1 on 2025-01-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0027_remove_prize_participant_remove_prize_prize_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.createevents')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.staff_registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.student_registration')),
            ],
        ),
    ]
