# Generated by Django 5.1 on 2025-01-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0029_alter_student_registration_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_registration',
            name='department',
            field=models.CharField(blank=True, choices=[('Information_Technology', 'INFORMATION_TECHNOLOGY'), ('Computer_Science', 'COMPUTER_SCIENCE'), ('Computer_Technology', 'COMPUTER_TECHNOLOGY'), ('Biotechnology', 'BIOTECHNOLOGY'), ('Physics', 'PHYSICS'), ('Chemistry', 'CHEMISTRY'), ('Mathematics', 'MATHEMATICS'), ('Environmental_Science', 'ENVIRONMENTAL_SCIENCE'), ('Astronomy', 'ASTRONOMY'), ('Microbiology', 'MICROBIOLOGY'), ('Genetics', 'GENETICS'), ('Biochemistry', 'BIOCHEMISTRY'), ('Geology', 'GEOLOGY'), ('Botany', 'BOTANY'), ('Zoology', 'ZOOLOGY'), ('Psychology', 'PSYCHOLOGY'), ('Neuroscience', 'NEUROSCIENCE'), ('Applied_Physics', 'APPLIED_PHYSICS'), ('Astronomical_Sciences', 'ASTRONOMICAL_SCIENCES'), ('Marine_Biology', 'MARINE_BIOLOGY'), ('Forensic_Science', 'FORENSIC_SCIENCE'), ('Business_Administration', 'BUSINESS_ADMINISTRATION'), ('Commerce', 'COMMERCE'), ('Economics', 'ECONOMICS'), ('Accountancy', 'ACCOUNTANCY'), ('Finance', 'FINANCE'), ('Marketing', 'MARKETING'), ('Business_Law', 'BUSINESS_LAW'), ('International_Business', 'INTERNATIONAL_BUSINESS'), ('Taxation', 'TAXATION'), ('Entrepreneurship', 'ENTREPRENEURSHIP')], max_length=25, null=True),
        ),
    ]
